# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Messenger(object):
    def setupUi(self, Messenger):
        Messenger.setObjectName("Messenger")
        Messenger.resize(340, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Messenger.sizePolicy().hasHeightForWidth())
        Messenger.setSizePolicy(sizePolicy)
        Messenger.setMinimumSize(QtCore.QSize(340, 340))
        Messenger.setMaximumSize(QtCore.QSize(340, 340))
        self.centralwidget = QtWidgets.QWidget(Messenger)
        self.centralwidget.setObjectName("centralwidget")
        self.sendMsg = QtWidgets.QPushButton(self.centralwidget)
        self.sendMsg.setGeometry(QtCore.QRect(280, 280, 40, 40))
        self.sendMsg.setObjectName("sendMsg")
        self.inputMsg = QtWidgets.QTextEdit(self.centralwidget)
        self.inputMsg.setGeometry(QtCore.QRect(20, 280, 250, 40))
        self.inputMsg.setObjectName("inputMsg")
        self.outputMsg = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputMsg.setGeometry(QtCore.QRect(20, 60, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.outputMsg.setFont(font)
        self.outputMsg.setObjectName("outputMsg")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(220, 20, 100, 20))
        self.inputName.setObjectName("inputName")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(155, 20, 60, 20))
        self.labelName.setObjectName("labelName")
        self.labelMessenger = QtWidgets.QLabel(self.centralwidget)
        self.labelMessenger.setGeometry(QtCore.QRect(20, 8, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelMessenger.setFont(font)
        self.labelMessenger.setObjectName("labelMessenger")
        Messenger.setCentralWidget(self.centralwidget)

        self.retranslateUi(Messenger)
        QtCore.QMetaObject.connectSlotsByName(Messenger)

    def retranslateUi(self, Messenger):
        _translate = QtCore.QCoreApplication.translate
        Messenger.setWindowTitle(_translate("Messenger", "MainWindow"))
        self.sendMsg.setText(_translate("Messenger", ">"))
        self.inputMsg.setPlaceholderText(_translate("Messenger", "Введите текст сообщения..."))
        self.labelName.setText(_translate("Messenger", "Ваше имя:"))
        self.labelMessenger.setText(_translate("Messenger", "Messenger"))
